Add SUSE Manager Server PAYG recipes
SUSE-Enceladus/keg-recipes pull request #244
Opened 2023-08-22 16:14 UTC by jgleissner

Note: This changes the source name of the SUSE Manager Server BYOS definitions and hence the `_service` files will need to be update once this is merged.

2023-08-29 16:36 UTC, jgleissner commented
I've split the Azure and EC2 profiles into llc and ltd versions. Since the PAYG and the BYOS descriptions don't have much in common anymore I moved the PAYG into an independent directory, which also has the advantage that existing `_service` files don't need to be modified.

2023-09-01 11:34 UTC, aosthof requested changes

2023-09-01 11:34 UTC, aosthof commented on images/cross-cloud/suse-manager/server-ondemand/content.yaml
> +        - suma-amazon-adapter-config-llc
The package `suma-amazon-adapter-config-llc` is only to be included in the `EC2-llc` profile. For Azure, the equivalent package is named  `suma-azure-adapter-config-llc` and should be put into a separate `Azure-llc` profile section. Same applies for the `ltd` version of those packages. Although the Azure packages are available in Devel:PubCloud:Azure they're still empty as we need to properly setup the offer in Azure first.

From my pov this should look like:

```
    - _attributes:
        type: image
        profiles: [EC2-llc]
      package:
        - suma-amazon-adapter-config-llc
    - _attributes:
        type: image
        profiles: [EC2-ltd]
      package:
        - suma-amazon-adapter-config-ltd
    - _attributes:
        type: image
        profiles: [Azure-llc]
      package:
        - suma-azure-adapter-config-llc
    - _attributes:
        type: image
        profiles: [Azure-ltd]
      package:
        - suma-azure-adapter-config-ltd
```

2023-09-01 11:34 UTC, aosthof commented on data/products/suse-manager/server/ondemand/sle15/packages.yaml
Not sure where exactly this belongs into, but we need to make sure the following `-release` packages are included:

```
        <!-- begin namespace manager_server_release -->
        <package name="SUSE-Manager-Server-release"/>
        <!-- end namespace manager_server_release -->
        <!-- begin namespace manager_server_modules -->
        <package name="sle-module-basesystem-release"/>
        <package name="sle-module-containers-release"/>
        <package name="sle-module-server-applications-release"/>
        <package name="sle-module-suse-manager-server-release"/>
        <package name="sle-module-web-scripting-release"/>
```
At least these are the corresponding `-release` package to the channels/repos a user gets when registering a BYOS version of SUMa.

2023-09-01 11:34 UTC, aosthof commented on data/products/suse-manager/server/ondemand/sle15/packages.yaml
> +      - billing-data-service
IIUC we also need to include the package `csp-billing-adapter-service`

2023-09-01 11:34 UTC, aosthof commented on data/csp/azure/settings/suma-server/ondemand/sle15/packages.yaml
> +      - python3-csp-billing-adapter-azure
Don't ask me why, but the correct package name is `python3-csp-billing-adapter-microsoft`

2023-09-01 12:27 UTC, rjschwei commented
PAYG has a different motd as well

2023-09-01 16:45 UTC, jgleissner commented
Ok, updated according to comments. Thanks.

2023-09-01 17:41 UTC, rjschwei approved these changes

2023-09-04 10:27 UTC, aosthof approved these changes
LGTM now.

2023-09-05 12:50 UTC, merged