Add SUSE Manager 5.0 PAYG recipe
SUSE-Enceladus/keg-recipes pull request #316
Opened 2024-05-09 09:21 UTC by jgleissner

Add SUSE Manager 5.0 PAYG recipe.
Add storage setup scripts to SUSE Manager 5.0.

2024-05-09 11:30 UTC, rjschwei commented
We want to get https://github.com/SUSE-Enceladus/susemanager-cloud-setup/pull/10 merged and then the new scripts go to the overlay directory. The old scripts do not work with SUMa in a container.

2024-05-09 11:33 UTC, rjschwei requested changes
Overlay scripts are not correct

2024-05-10 16:05 UTC, jgleissner commented
Scripts updated.

2024-05-10 19:03 UTC, rjschwei approved these changes

2024-05-10 19:03 UTC, merged