Increase default and max socket buffer sizes (bcs#1223566)
SUSE-Enceladus/keg-recipes pull request #382
Opened 2024-10-23 15:15 UTC by jgleissner

This increases the default socket buffer size to 1048576 bytes as requested in bsc#1223566 and the max to 2500000 bytes (as newer kernels use as default) for all Azure images. Should this perhaps be set for all platforms to be uniform? Also, should this be limited to SLES for SAP only (the platform the bug was reported for)?

2024-10-24 11:37 UTC, rjschwei commented
Based on my understanding these settings are sensitive to the underlying network device as such generalizing them to all CSPs is probably not what we want to do. We should limit the setting to SLES4SAP as allocation of a larger buffer will trigger memory pressure elsewhere. SAP workloads are expected to run on instances with ample memory and as such this should not be a problem, however for everything else this is not the case as such we should target SLES4SAP.

2024-10-24 11:38 UTC, rjschwei requested changes
Please add as SLES4SAP specific change. Thanks

2024-10-24 13:55 UTC, jgleissner commented
> Please add as SLES4SAP specific change. Thanks

Ok. After thinking about it some more, we could also only increase the max buffer size, which is 212992 bytes on SLES 15 by default (which works out to twice the size of the default weirdly because buffer sizes set via `setsockopt()` get doubled). Increasing the default buffer size would just waste kernel memory in systems that don't need it, and ironically could even lead to more packet drops if the kernel is pressed for memory.

I think it's reasonable to assume that applications that benefit from a larger receive buffer request one, and in case of UDP (which is specifically mentioned in the bug report), it very much depends on the application how to handle packet loss.

What do you think @rjschwei ?

2024-10-24 17:30 UTC, rjschwei commented
> > Please add as SLES4SAP specific change. Thanks
> 
> Ok. After thinking about it some more, we could also only increase the max buffer size, which is 212992 bytes on SLES 15 by default (which works out to twice the size of the default weirdly because buffer sizes set via `setsockopt()` get doubled). Increasing the default buffer size would just waste kernel memory in systems that don't need it, and ironically could even lead to more packet drops if the kernel is pressed for memory.
> 
> I think it's reasonable to assume that applications that benefit from a larger receive buffer request one, 


This I don't think is true or we probably wouldn't have this request.


> and in case of UDP (which is specifically mentioned in the bug report), it very much depends on the application how to handle packet loss.
> 
> What do you think @rjschwei ?

Well if we only update the max buffer size then the default would remain at whatever we build in and if the application doesn't ask for more, which I expect to be the case then we are stuck with the same problem we have today. As such I think that changing the default is the "safer" approach to meet the needs of the applications. Ultimately this is a convenience for the admin of the system and one cold look at this as a kind of pre-tuning. Which is also the reason I would narrow this to the image(s) (SLES4SAP) where we expect workloads that most likely benefit from this setting and that will run on instances where sufficient memory exists.

2024-10-24 17:51 UTC, jgleissner commented
Fair points. I feel making buffers bigger by default isn't a particularly good practice, but potentially wasting a few MB per socket on a machine designed to handle SAP workloads will probably be insignificant. I'll update the PR.

2024-10-25 15:22 UTC, rjschwei approved these changes

2024-10-25 15:22 UTC, merged